#!/bin/bash

PROMPT='given the text below is a receipt, extract a CSV with the following columns: merchant name which is likely to be a single word, receipt date in dd/mm/yyyy HH:mm format, summary of what was purchased, total of the receipt. Respond with a single line representing the CSV data'

# region Functions
  process_scan() {
    # Get path to current file
    local scan_full_path
    scan_full_path="$1" # Full path: /usr/file/receipt.jpg

    # Trim 20px border from image
    echo "Trimming ..."
    magick "$scan_full_path" -shave 20x20 "$scan_full_path" > /dev/null 2>&1

    # Replace background color to black
    echo "Adjusting background color..."
    magick "$scan_full_path" -fuzz 20% -transparent "$INPUT_BG_COLOR" -background "#000000" -flatten "$scan_full_path" > /dev/null 2>&1
    # Add a border to help multi crop
    convert "$scan_full_path" -bordercolor "#000000" -border "50x50" "$scan_full_path" > /dev/null 2>&1
    # Convert image to binary
    magick "$scan_full_path" -alpha off -auto-threshold otsu "$scan_full_path"

    # Split input file
    echo "Splitting image..."
    multicrop2 -b "#000000" -f 40 -u 3 -t 10 -d 200 "$scan_full_path" "$tempDir/split.jpg" > /dev/null 2>&1
    rm "$scan_full_path"

    # Process split
    echo "Processing splits..."
    local splitIndex=1
    local fileName
    local csvContent

    for filePath in "$tempDir"/*.jpg; do
      if [ -f "$filePath" ]; then
        echo "Processing split #$splitIndex..."

        # Extract text
        echo "Extracting text..."
        fileName=$(basename "$filePath" .jpg)
        tesseract "$filePath" "$tempDir/$fileName" -l eng > /dev/null 2>&1

        # Prepend prompt to file
        echo "Adding prompt to file..."
        echo "" | cat - "$tempDir/$fileName".txt > temp && mv temp "$tempDir/$fileName".txt
        echo "" | cat - "$tempDir/$fileName".txt > temp && mv temp "$tempDir/$fileName".txt
        echo "$PROMPT" | cat - "$tempDir/$fileName".txt > temp && mv temp "$tempDir/$fileName".txt

        # Parse text and get CSV
        echo "Running AI magick..."
        csvContent=$(fabric --pattern export_data_as_csv < "$OUTPUT_DIRECTORY/tmp/$fileName".txt | tail -n1)
        # Convert to lowercase
        csvContent=$(tr '[:upper:]' '[:lower:]' <<< "$csvContent")

        echo "Saving CSV line..."
        echo "$csvContent" >> "$OUTPUT_DIRECTORY/data.csv"

        # Rename image
        echo "Saving receipt image..."
        IFS=',' read -ra csvData <<< "$csvContent"
        local imageName
        local merchant
        local date
        merchant="${csvData[0]// /-}"

        date="${csvData[1]// /_}"
        date="${date//\//-}"
        date="${date//:/-}"

        imageName="${merchant}_${date}.jpg"
        imageName="${imageName//\"/}"

        # Move split image into Merchant directory
        mkdir -p "$OUTPUT_DIRECTORY/$merchant"
        # Rename file to include merchant name and date
        cp "$filePath" "$OUTPUT_DIRECTORY/$merchant/$imageName"

        # Continue
        splitIndex=$((splitIndex + 1))
      fi
    done
  }

  pause_execution() {
    # Set the input variable to an empty string initially
    local input=""

    # The '-r' flag prevents backslash interpretation
    # The '-p' flag allows us to specify a prompt
    read -r -p "Press [Enter] to scan a new document, or 's' to end scanning: " input

    # Check the input provided by the user.
    # If the user presses ENTER only, 'input' will be empty, and we continue the loop.
    if [[ "$input" =~ ^[sS]$ ]]; then
      # If input is 's' or 'S', return 1 (indicating a stop condition)
      return 1
    else
      # Otherwise (Enter or any other key), return 0 (indicating continue)
      return 0
    fi
  }
# endregion

# region MainScript
  # Check if the correct number of parameters were provided
  if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <OUTPUT_DIRECTORY> <BG_COLOR>" >&2
    exit 1
  fi

  # Directory to write files to
  OUTPUT_DIRECTORY=$(realpath -q "$1")
  # Background colour of scanner plate
  INPUT_BG_COLOR="$2"

  # Create directory if not exist
  if [ ! -d "$OUTPUT_DIRECTORY" ]; then
    mkdir -p "$OUTPUT_DIRECTORY"
  fi

  # Create CSV file if not exists
  if [ ! -f "$OUTPUT_DIRECTORY/data.csv" ]; then
    echo "merchant,date,summary,total" >> "$OUTPUT_DIRECTORY/data.csv"
  fi

  while pause_execution; do
    # Create temporary directory
    tempDir="$(mktemp -d)"

    echo "Connecting to scanner..."
    # Capture images from scanner
    scanline \
      -a4 \
      -resolution 300 \
      -flatbed \
      -jpeg \
      -dir "$tempDir" \
      -name "scan"

    echo "Processing scan..."
    if [ -f "$tempDir/scan.jpg" ]; then
      process_scan "$tempDir/scan.jpg"
    fi

    echo "Cleaning up..."
    rm -rf "$tempDir"
  done;
# endregion
